# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-11 02:09
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=django_markdown.models.MarkdownField(verbose_name='Contents'),
        ),
    ]
